[Interface]
Address = 10.66.0.10/32
PrivateKey = SHN5l9msRH17/s9vpdJb8mkLi7oFcmfF6HZbppU4VH0=

[Peer]
PublicKey = UfCALyEgqveBfI/YZn5oEHIvzm8ge718sL0wmh3NsGk=
Endpoint = 127.0.0.1:51820
AllowedIPs = 10.66.0.1/32
PersistentKeepalive = 25