[Interface]
Address = 10.66.0.10/32
PrivateKey = wM40n+P6wGH3lM/5exeBtD/g48aBWztE+DTFXxvwW0U=

[Peer]
PublicKey = UfCALyEgqveBfI/YZn5oEHIvzm8ge718sL0wmh3NsGk=
Endpoint = 127.0.0.1:51820
AllowedIPs = 10.66.0.1/32
PersistentKeepalive = 25